### ISSUE TITLE
abyme yarn package doesn't import in 0.3.1

### ISSUE THREAD

**Issue by joshleblanc** [eki-177/abyme#39]
Looks like the package.json is specifying the exports are in a file that doesn't exist in the dist folder. Only `abyme.js` exists, no umd, modern, etc files.

```
index.js:10 Uncaught Error: Cannot find module 'abyme'
```

`0.2.5` imports fine.

**Comment by bear-in-mind** [comment]
So from what I tried in my various projects, re-bundling seems to have solved the issue. I know it was long overdue, but if you want to confirm that it works for you, it would be awesome :) Thanks @joshleblanc 🙏
